# Generated by Django 4.2.1 on 2023-05-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='numbers',
        ),
    ]
