# Generated by Django 4.2.1 on 2023-06-08 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_Name', models.CharField(max_length=200)),
                ('p_Type', models.CharField(max_length=20)),
                ('p_Amount', models.CharField(max_length=20)),
                ('p_Phone', models.CharField(max_length=20)),
                ('p_TransactionID', models.CharField(max_length=30)),
                ('p_Date', models.CharField(max_length=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='ticket.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ticket.payment'),
        ),
    ]
