# Generated by Django 4.2.1 on 2023-05-26 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_order_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.order'),
        ),
    ]
