# Generated by Django 4.2.1 on 2023-05-26 03:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(max_length=10), blank=True, null=True, size=None),
        ),
    ]
